### ISSUE TITLE
README.org is not a markdown file

### ISSUE THREAD

**Issue by PythonLinks** [sillygod/cdp-cache#56]
I would like to edit the README file, but since it ends in .org, the browser based editor does not work on it.  Could we rename it to README.md.  That would make contributing to the documentation much easier. 

Let me also point out that I updated the caddy template readme on bastille.

**Comment by PythonLinks** [comment]
Oops, here is the link. 
https://gitlab.com/PythonLinks/caddy

**Comment by sillygod** [comment]
Hi, @PythonLinks  thanks for your endeavoring to revise the readme file.  About the format of the readme file, I still prefer the org file because It has more functionalities than the markdown.

May I know how the browser-based editor not to work on the org file? I don't get it clearly.

>Let me also point out that I updated the caddy template readme on bastille.

BTW, it's cool

**Comment by PythonLinks** [comment]
Thank you. 
Okay so README.org is in something called org mode.  It looks like the github online editor web preview  does handle it correctly.  As does emacs.  So I apologize, I was no aware of it.  README.org is is fine. 
 Live and learn.
